apiVersion: meta.pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: example-control-plane
spec:
  crossplane:
    version: ">=v1.14.1-0"
  dependsOn:
  - provider: xpkg.upbound.io/upbound/provider-aws-rds
    version: "v1.1.1"
  - provider: xpkg.upbound.io/upbound/provider-aws-ec2
    version: "v1.1.1"
  - function: xpkg.upbound.io/crossplane-contrib/function-patch-and-transform
    version: "v0.3.0"
  # The init block specifies a type of XR that the package manager can
  # optionally create to initialize this Configuration. The XR is specified
  # inline when the Configuration is installed. 
  init:
    compositeTypeRef:
      apiVersion: example.crossplane.io/v1
      Kind: XInitConfig
