apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xinitconfigs.aws.platform.upbound.io
spec:
  group: aws.platform.upbound.io
  names:
    kind: XInitConfig
    plural: xinitconfigs
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                irsaRoleARN:
                  type: string
                vaultServer:
                  type: string
              required:
                - vaultServer
                - irsaRoleARN